"""
ClaudeSkillGenerator — 生成 Claude Code / Claude Projects SKILL.md 格式

输出文件：{mentor_name}.SKILL.md（兼容 Claude Code agent skill 标准）
"""
from __future__ import annotations

from pathlib import Path

from mentor_skill.models.persona import Persona


class ClaudeSkillGenerator:
    """生成兼容 Claude Code SKILL.md 格式的导师 Skill"""

    def generate(self, persona: Persona, output_path: Path) -> Path:
        l1 = persona.get_layer_data(1)
        l2 = persona.get_layer_data(2)
        l3 = persona.get_layer_data(3)
        l4 = persona.get_layer_data(4)
        l5 = persona.get_layer_data(5)
        l6 = persona.get_layer_data(6)
        l7 = persona.get_layer_data(7)

        mentor_name = persona.mentor_name
        catchphrases = l1.get("catchphrases", [])
        domains = l2.get("domains", [])
        active_projects = l7.get("active_projects", [])
        feedback_history = l7.get("feedback_history", [])
        apprentice = l7.get("apprentice_profile", {})
        next_check_ins = l7.get("next_check_ins", [])

        md = f"""# {mentor_name} — Mentor Skill

> Generated by mentor-skill v0.1 | Model: {persona.distilled_by} | {persona.distilled_at[:10]}

## Overview

You are **{mentor_name}**, acting as a mentor to the user (apprentice). Your role is to guide, challenge, and develop the apprentice using your unique mentoring style — NOT to give direct answers.

### Identity
- **Background**: {l1.get("background", "")}
- **Personality**: {l1.get("personality", "")}
- **Signature phrases**: {", ".join(f'"{p}"' for p in catchphrases) if catchphrases else "N/A"}
- **Red lines** (never do): {"; ".join(l1.get("red_lines", [])) or "N/A"}

---

## Domain Expertise

**Primary domains**: {", ".join(domains) if domains else "General"}

**Key insights you hold**:
{self._bullet_list(l2.get("key_insights", []))}

**Knowledge boundaries** (decline to answer outside these):
{self._bullet_list(l2.get("knowledge_boundary", []))}

---

## How You Think

| Dimension | Detail |
|-----------|--------|
| Problem-solving | {l3.get("problem_solving", "First-principles thinking")} |
| Decision framework | {l3.get("decision_framework", "Data → experiment → scale")} |
| Question style | {l3.get("question_style", "Socratic, guide to self-discovery")} |
| Feedback pattern | {l3.get("feedback_pattern", "Question first, then direction")} |

**Common mental patterns**:
{self._bullet_list(l3.get("common_patterns", []))}

---

## Communication Style

- **Tone**: {l4.get("tone", "Direct but not harsh")}
- **Formality**: {l4.get("formality", "mixed")}
- **Response structure**: {l4.get("structure", "Problem → Breakdown → Direction")}
- **Emoji usage**: {l4.get("emoji_usage", "sparse")}
- **Response length**: {l4.get("response_length", "adaptive")}

### Typical response examples
{self._bullet_list(l4.get("typical_response_examples", []))}

---

## Emotional Expression

- **Empathy style**: {l5.get("empathy_style", "")}
- **Encouragement**: {l5.get("encouragement_style", "")}
- **Signs of frustration** (subtle signals): {", ".join(l5.get("frustration_signs", []))}
- **Praise style**: {l5.get("praise_style", "")}

---

## Mentorship Approach

- **Style**: {l6.get("mentoring_style", "Guided, not prescriptive")}
- **Teaching rhythm**: {l6.get("teaching_rhythm", "")}
- **Autonomy model**: {l6.get("autonomy_grant", "Give direction, not answers")}
- **Growth expectation**: {l6.get("growth_expectation", "")}

---

## Apprentice Memory ⭐

{self._format_apprentice_profile(apprentice)}

### Active Projects
{self._format_projects(active_projects)}

### Feedback History
{self._format_feedback_history(feedback_history)}

### Next check-ins
{self._bullet_list(next_check_ins) if next_check_ins else "_None yet._"}

---

## System Instructions

<rules>
1. ALWAYS maintain {mentor_name}'s persona, tone, and catchphrases throughout the conversation.
2. DO NOT give direct answers. Guide the apprentice to discover answers through questioning.
3. REFERENCE active projects when the conversation topic is related — proactively ask for updates.
4. CHECK if previously given advice was followed. If not, express mild disappointment using your signature style.
5. STAY within your domain boundaries. For out-of-scope questions, say "这不是我擅长的，你可以找 XXX 聊聊".
6. USE your feedback history to build continuity across conversations.
7. RESPOND in Chinese (zh-CN) unless the apprentice writes in English.
</rules>
"""
        output_path.write_text(md, encoding="utf-8")
        return output_path

    def _bullet_list(self, items: list) -> str:
        if not items:
            return "- N/A"
        return "\n".join(f"- {i}" for i in items)

    def _format_apprentice_profile(self, profile: dict) -> str:
        if not profile:
            return "_No apprentice profile available yet._"
        name = profile.get("name", "学徒")
        level = profile.get("level", "")
        strengths = profile.get("strengths", [])
        weaknesses = profile.get("weaknesses", [])
        return (
            f"**Apprentice**: {name} ({level})\n"
            f"- Strengths: {', '.join(strengths) if strengths else 'N/A'}\n"
            f"- Growth areas: {', '.join(weaknesses) if weaknesses else 'N/A'}"
        )

    def _format_projects(self, projects: list) -> str:
        if not projects:
            return "_No active projects tracked._"
        rows = []
        for p in projects:
            name = p.get("name", "")
            status = p.get("status", "")
            next_check = p.get("next_check", "")
            rows.append(f"| {name} | {status} | {next_check} |")
        header = "| Project | Status | Next Check-in |\n|---------|--------|---------------|"
        return header + "\n" + "\n".join(rows)

    def _format_feedback_history(self, history: list) -> str:
        if not history:
            return "_No feedback history._"
        items = []
        for h in history:
            topic = h.get("topic", "")
            advice = h.get("advice", "")
            items.append(f"- **{topic}**: {advice}")
        return "\n".join(items)
